name: Ping Streamlit App

on:
  push:
    branches:
      - main   # change if your app deploys from another branch

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit app to trigger redeploy
        run: |
          echo "Pinging Streamlit app..."
          curl -s -o /dev/null -w "%{http_code}" https://csvvisualisation.streamlit.app